#!/usr/bin/env node
/**
 * MPAS Bridge MCP Server
 * Generated by bridge-generator
 *
 * This file is generated then checked in. Edit freely.
 *
 * Conforms to the MPAS MCP Proposer Bridge Client Interface Profile v0.1:
 * application calls return control as soon as the Action is durably recorded,
 * the workflow advances on a background loop, and results are retrieved
 * through the reserved mpas_wait_for_action_result tool.
 */

import { readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import {
  ActionPackageBuilder,
  AdapterClient,
  CoordinationClient,
  KeyManager,
  MemoryWorkflowStore,
  ProposerBridge,
} from "@oma3/mpas";
import type {
  BridgeUpstreamTool,
  MpasApplicationPlugin,
  ProposerConfig,
  ToolCallResult,
  WorkflowCoordination,
  WorkflowStore,
} from "@oma3/mpas";
import { SqliteWorkflowStore } from "./sqlite-workflow-store.js";

const TOOLS = loadTools();

interface WorkflowConfig {
  /** SQLite database path. Omitted → in-memory store (no restart durability). */
  dbPath?: string;
  /** Minimum post-resolution retention disclosed to clients. Default 86400. */
  resultRetentionSeconds?: number;
  /** Background tick interval. Default 2000ms. */
  pollIntervalMs?: number;
  /** Deployment assigns maintainer notification to the bridge or another component. */
  notificationAssignedElsewhere?: boolean;
}

interface BridgeConfig extends Omit<ProposerConfig, "approvalStrategy" | "approvalTimeoutMs"> {
  workflow?: WorkflowConfig;
}

interface CliConfig {
  mode?: "proposer" | "maintainer";
  plugin?: string;
  adapter?: {
    url?: string;
  };
  coordination?: {
    url?: string;
  };
  agent?: {
    did?: string;
    keyFile?: string;
  };
  target?: {
    applicationDid?: string;
  };
  applicationDid?: string;
  adapterUrl?: string;
  agentKey?: string;
  executionProfile?: {
    id: string;
    format: string;
  };
  workflow?: WorkflowConfig;
  defaultExpirationMinutes?: number;
  /** @deprecated The bridge always returns a deferred result; no synchronous approval wait exists. */
  approvalStrategy?: string;
  /** @deprecated See approvalStrategy. */
  approvalTimeoutMs?: number;
}

function log(level: "info" | "warn" | "error", msg: string, data?: object): void {
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  process.stderr.write(`[mpas-bridge] ${JSON.stringify(entry)}\n`);
}

export class GeneratedBridge {
  private readonly bridgePromise: Promise<ProposerBridge>;
  private readonly store: WorkflowStore;

  constructor(config: BridgeConfig) {
    const plugin = loadPlugin(config.plugin);
    const adapterClient = new AdapterClient({ url: config.adapterUrl });
    const coordination: WorkflowCoordination = config.coordinationUrl
      ? new CoordinationClient({ url: config.coordinationUrl })
      : unconfiguredCoordination();
    const keyManagerPromise = loadKeyManager(config.agentKey);
    const workflow = config.workflow ?? {};
    this.store = workflow.dbPath ? new SqliteWorkflowStore(workflow.dbPath) : new MemoryWorkflowStore();
    if (!workflow.dbPath) {
      log("warn", "memory_workflow_store", {
        note: "No workflow.dbPath configured; active Actions will not survive a bridge restart.",
      });
    }

    this.bridgePromise = keyManagerPromise.then((keyManager) => {
      const executionProfile = config.executionProfile ?? {
        id: plugin.executionProfile.id,
        format: plugin.executionProfile.format ?? "mcp.toolsCall",
      };
      return new ProposerBridge({
        tools: [...TOOLS],
        buildActionPackage: (toolName, args) =>
          new ActionPackageBuilder({
            applicationDid: config.applicationDid,
            executionProfile,
            keyManager,
            ...(config.defaultExpirationMinutes !== undefined
              ? { defaultExpirationMinutes: config.defaultExpirationMinutes }
              : {}),
          }).buildFromToolCall(toolName, args),
        store: this.store,
        adapter: adapterClient,
        coordination,
        proposerDid: keyManager.did,
        resultRetentionSeconds: workflow.resultRetentionSeconds ?? 86_400,
        ...(workflow.notificationAssignedElsewhere !== undefined
          ? { notificationAssignedElsewhere: workflow.notificationAssignedElsewhere }
          : {}),
        ...(workflow.pollIntervalMs !== undefined ? { pollIntervalMs: workflow.pollIntervalMs } : {}),
      });
    });
  }

  getToolDefinitions(): BridgeUpstreamTool[] {
    // Static surface: profile notices and unions are deterministic, so expose
    // them without awaiting the key manager.
    return new ProposerBridge({
      tools: [...TOOLS],
      buildActionPackage: () => Promise.reject(new Error("static surface only")),
      store: new MemoryWorkflowStore(),
      adapter: { submit: () => Promise.reject(new Error("static surface only")) },
      coordination: unconfiguredCoordination(),
      proposerDid: "did:static",
      resultRetentionSeconds: 86_400,
    }).getToolDefinitions();
  }

  async handleToolCall(toolName: string, args: object): Promise<ToolCallResult> {
    log("info", "tool_call_received", { toolName });
    const bridge = await this.bridgePromise;
    const result = await bridge.handleToolCall(toolName, args);
    return result as ToolCallResult;
  }

  /** Startup reconciliation plus the background workflow loop. */
  async start(): Promise<void> {
    const bridge = await this.bridgePromise;
    await bridge.start();
    log("info", "bridge_started");
  }

  stop(): void {
    void this.bridgePromise.then((bridge) => {
      bridge.stop();
      this.store.close();
    });
  }

  buildMcpServer(): Server {
    const server = new Server(
      {
        name: "plain-mcp-mpas-bridge",
        version: "2.0.0",
      },
      {
        capabilities: {
          tools: {},
        },
      },
    );

    server.setRequestHandler(ListToolsRequestSchema, () => ({
      tools: this.getToolDefinitions(),
    }));
    server.setRequestHandler(CallToolRequestSchema, async (request) =>
      this.handleToolCall(request.params.name, toArgsObject(request.params.arguments)),
    );

    return server;
  }
}

/**
 * Placeholder used when no coordinationUrl is configured. Approval-gated
 * Actions stay durably recorded in created/awaitingApprovals and are retried
 * by reconciliation; they cannot complete until coordination exists.
 */
function unconfiguredCoordination(): WorkflowCoordination {
  return {
    submitAction() {
      return Promise.reject(new Error("Coordination Service is not configured (coordination.url)."));
    },
    poll() {
      return Promise.resolve({
        version: "1" as const,
        type: "CoordinationPollResponse" as const,
        approvalRequests: [],
        actionUpdates: [],
      });
    },
  };
}

export async function createBridgeFromConfig(configPath: string): Promise<GeneratedBridge> {
  const absoluteConfigPath = resolve(configPath);
  const configDir = dirname(absoluteConfigPath);
  const config = JSON.parse(await readFile(absoluteConfigPath, "utf8")) as CliConfig;
  return new GeneratedBridge(toBridgeConfig(config, configDir));
}

export async function runBridge(argv = process.argv.slice(2)): Promise<void> {
  const configPath = configPathFromArgs(argv);
  const bridge = await createBridgeFromConfig(configPath);
  const server = bridge.buildMcpServer();
  const transport = new StdioServerTransport();

  await bridge.start();
  await server.connect(transport);
}

function toBridgeConfig(config: CliConfig, configDir: string): BridgeConfig {
  if (config.mode === "maintainer") {
    throw new Error("Maintainer/signer mode is not supported by this proposer bridge.");
  }
  if (!config.plugin) {
    throw new Error('Proposer bridge config requires "plugin".');
  }
  if (config.approvalStrategy !== undefined || config.approvalTimeoutMs !== undefined) {
    log("warn", "deprecated_config_ignored", {
      note: "approvalStrategy/approvalTimeoutMs are ignored: the bridge always returns a deferred result and serves results via mpas_wait_for_action_result.",
    });
  }
  const pluginPath = resolve(configDir, config.plugin);
  const plugin = loadPlugin(pluginPath);
  const adapterUrl = config.adapter?.url ?? config.adapterUrl;
  const agentKey = config.agent?.keyFile ?? config.agentKey;
  if (!adapterUrl) {
    throw new Error('Proposer bridge config requires "adapter.url".');
  }
  if (!agentKey) {
    throw new Error('Proposer bridge config requires "agent.keyFile".');
  }

  const workflow: WorkflowConfig = { ...config.workflow };
  if (workflow.dbPath) {
    workflow.dbPath = resolve(configDir, workflow.dbPath);
  }

  return {
    plugin: pluginPath,
    applicationDid: (config.target?.applicationDid ?? config.applicationDid ?? plugin.applicationDid) as BridgeConfig["applicationDid"],
    adapterUrl,
    agentKey: resolve(configDir, agentKey),
    coordinationUrl: config.coordination?.url,
    executionProfile: (config.executionProfile ?? {
      id: plugin.executionProfile.id,
      format: plugin.executionProfile.format ?? "mcp.toolsCall",
    }) as BridgeConfig["executionProfile"],
    defaultExpirationMinutes: config.defaultExpirationMinutes,
    workflow,
  };
}

function loadTools(): BridgeUpstreamTool[] {
  const raw = readFileSync(new URL("./tools.json", import.meta.url), "utf8");
  return JSON.parse(raw) as BridgeUpstreamTool[];
}

function loadPlugin(plugin: BridgeConfig["plugin"]): MpasApplicationPlugin {
  if (typeof plugin === "string") {
    return JSON.parse(readFileSync(plugin, "utf8")) as MpasApplicationPlugin;
  }

  return plugin;
}

function loadKeyManager(agentKey: BridgeConfig["agentKey"]): Promise<KeyManager> {
  if (typeof agentKey === "string") {
    return KeyManager.fromFile(agentKey);
  }

  return Promise.resolve(KeyManager.fromJwk(agentKey));
}

function configPathFromArgs(argv: string[]): string {
  const configIndex = argv.indexOf("--config");
  const configPath = configIndex >= 0 ? argv[configIndex + 1] : undefined;
  if (!configPath) {
    throw new Error("Usage: mpas-bridge --config <path>");
  }

  return configPath;
}

function toArgsObject(args: unknown): object {
  if (args && typeof args === "object" && !Array.isArray(args)) {
    return args;
  }

  return {};
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await runBridge();
}
