#!/usr/bin/env node
/**
 * MPAS Bridge MCP Server
 * Generated by bridge-generator
 * Upstream: docker run -i --rm -e GITHUB_PERSONAL_ACCESS_TOKEN ghcr.io/github/github-mcp-server
 *
 * This file is generated then checked in. Edit freely.
 */

import { readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import {
  ActionPackageBuilder,
  AdapterClient,
  CoordinationClient,
  KeyManager,
} from "@oma3/mpas";
import type {
  ActionReference,
  AdapterResponse,
  MpasApplicationPlugin,
  ProposerConfig,
  ToolCallResult,
} from "@oma3/mpas";

const TOOLS = loadTools();

interface CliConfig {
  mode?: "proposer" | "maintainer";
  plugin?: string;
  adapter?: {
    url?: string;
  };
  coordination?: {
    url?: string;
  };
  agent?: {
    did?: string;
    keyFile?: string;
  };
  target?: {
    applicationDid?: string;
  };
  applicationDid?: string;
  adapterUrl?: string;
  agentKey?: string;
  executionProfile?: {
    id: string;
    format: string;
  };
  approvalStrategy?: "return" | "coordinate" | "wait";
  approvalTimeoutMs?: number;
  defaultExpirationMinutes?: number;
}

function log(level: "info" | "warn" | "error", msg: string, data?: object): void {
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  process.stderr.write(`[mpas-bridge] ${JSON.stringify(entry)}\n`);
}

export class GeneratedBridge {
  private readonly plugin: MpasApplicationPlugin;
  private readonly adapterClient: AdapterClient;
  private readonly coordinationClient?: CoordinationClient;
  private readonly keyManagerPromise: Promise<KeyManager>;

  constructor(private readonly config: ProposerConfig) {
    this.plugin = loadPlugin(config.plugin);
    this.adapterClient = new AdapterClient({ url: config.adapterUrl });
    this.coordinationClient = config.coordinationUrl ? new CoordinationClient({ url: config.coordinationUrl }) : undefined;
    this.keyManagerPromise = loadKeyManager(config.agentKey);
  }

  getToolDefinitions(): Tool[] {
    return [...TOOLS];
  }

  async handleToolCall(toolName: string, args: object): Promise<ToolCallResult> {
    log("info", "tool_call_received", { toolName });
    if (!TOOLS.some((tool) => tool.name === toolName)) {
      return errorResult("UNKNOWN_TOOL", `Unknown tool: ${toolName}`, { toolName });
    }

    const keyManager = await this.keyManagerPromise;
    const builder = new ActionPackageBuilder({
      applicationDid: this.config.applicationDid,
      executionProfile: this.config.executionProfile ?? {
        id: this.plugin.executionProfile.id,
        format: this.plugin.executionProfile.format ?? "mcp.toolsCall",
      },
      keyManager,
      defaultExpirationMinutes: this.config.defaultExpirationMinutes,
    });
    const actionPackage = await builder.buildFromToolCall(toolName, args);
    log("info", "submitting_to_adapter", { toolName, actionId: actionPackage.actionEnvelope.actionId.value });
    const response = await this.adapterClient.submit(actionPackage);
    log("info", "adapter_response", { toolName, result: response.result });

    return this.handleAdapterResponse(response, actionPackage);
  }

  buildMcpServer(): Server {
    const server = new Server(
      {
        name: "github-mcp-server-mpas-bridge",
        version: "v1.6.0",
      },
      {
        capabilities: {
          tools: {},
        },
      },
    );

    server.setRequestHandler(ListToolsRequestSchema, () => ({
      tools: this.getToolDefinitions(),
    }));
    server.setRequestHandler(CallToolRequestSchema, async (request) => {
      if (!TOOLS.some((tool) => tool.name === request.params.name)) {
        throw new Error(`Unknown tool: ${request.params.name}`);
      }
      return this.handleToolCall(request.params.name, toArgsObject(request.params.arguments));
    });

    return server;
  }

  private async handleAdapterResponse(response: AdapterResponse, actionPackage: Awaited<ReturnType<ActionPackageBuilder["buildFromToolCall"]>>): Promise<ToolCallResult> {
    if (response.result === "additionalApprovalsRequired") {
      return this.handleAdditionalApprovals(response, actionPackage);
    }
    return mapTerminalResponse(response);
  }

  private async handleAdditionalApprovals(
    response: AdapterResponse,
    actionPackage: Awaited<ReturnType<ActionPackageBuilder["buildFromToolCall"]>>,
  ): Promise<ToolCallResult> {
    const strategy = this.config.approvalStrategy ?? "wait";
    log("info", "additional_approvals_required", { strategy, hasCoordinationClient: !!this.coordinationClient });
    let coordinationActionRef: ActionReference | undefined;

    if (strategy === "coordinate" || strategy === "wait") {
      if (!this.coordinationClient) {
        log("error", "coordination_not_configured", { strategy });
        return errorResult("COORDINATION_NOT_CONFIGURED", "Approval strategy requires coordinationUrl.", response);
      }
      if (!response.authorizationRequirements) {
        log("error", "missing_auth_requirements");
        return errorResult("MISSING_AUTH_REQUIREMENTS", "additionalApprovalsRequired without authorizationRequirements.", response);
      }
      log("info", "submitting_to_coordination");
      const coordinationResponse = await this.coordinationClient.submitAction(
        actionPackage,
        response.authorizationRequirements,
      );
      coordinationActionRef = coordinationResponse.actionRef;
      log("info", "coordination_submitted", { actionEnvelopeHash: coordinationActionRef?.actionEnvelopeHash?.value });
    }

    if (strategy === "wait" && this.coordinationClient && coordinationActionRef) {
      log("info", "entering_wait_loop", { timeoutMs: this.config.approvalTimeoutMs ?? 300_000 });
      return this.waitForCoordinatedResult(
        actionPackage,
        coordinationActionRef.actionEnvelopeHash.value,
        response,
      );
    }

    return {
      content: [
        {
          type: "text",
          text: "Additional approvals required.",
        },
      ],
      structuredContent: {
        status: "pending",
        actionId: actionPackage.actionEnvelope.actionId.value,
        coordinationActionRef,
        authorizationRequirements: response.authorizationRequirements,
      },
    };
  }

  private async waitForCoordinatedResult(
    originalActionPackage: Awaited<ReturnType<ActionPackageBuilder["buildFromToolCall"]>>,
    actionEnvelopeHash: string,
    response: AdapterResponse,
  ): Promise<ToolCallResult> {
    const timeoutMs = this.config.approvalTimeoutMs ?? 300_000;
    const deadline = Date.now() + timeoutMs;
    const keyManager = await this.keyManagerPromise;

    while (Date.now() <= deadline) {
      try {
        const poll = await this.coordinationClient?.poll(keyManager.did);
        const update = poll?.actionUpdates.find(
          (candidate) => candidate.actionRef.actionEnvelopeHash.value === actionEnvelopeHash,
        );
        if (update?.state === "readyForResubmission" && update.actionPackage) {
          log("info", "resubmitting_approved_action");
          const adapterResponse = await this.adapterClient.submit(update.actionPackage);
          log("info", "resubmission_response", { result: adapterResponse.result });
          return this.handleResubmittedAdapterResponse(adapterResponse);
        }
        if (update?.state === "cancelled") {
          return errorResult("COORDINATED_ACTION_CANCELLED", "Coordinated action was cancelled.", { update });
        }
        if (update?.state === "expired") {
          return errorResult("COORDINATED_ACTION_EXPIRED", "Coordinated action expired before approvals were collected.", { update });
        }
      } catch (error) {
        log("error", "poll_error", { error: error instanceof Error ? error.message : String(error) });
      }

      await sleep(Math.min(2000, Math.max(100, deadline - Date.now())));
    }

    log("warn", "wait_timeout", { timeoutMs });
    return {
      content: [
        {
          type: "text",
          text: "Additional approvals still pending.",
        },
      ],
      structuredContent: {
        status: "pending",
        actionId: originalActionPackage.actionEnvelope.actionId.value,
        actionEnvelopeHash,
        authorizationRequirements: response.authorizationRequirements,
      },
    };
  }

  private async handleResubmittedAdapterResponse(response: AdapterResponse): Promise<ToolCallResult> {
    if (response.result === "additionalApprovalsRequired") {
      return {
        content: [
          {
            type: "text",
            text: "Additional approvals still required after resubmission.",
          },
        ],
        structuredContent: {
          status: "pending",
          authorizationRequirements: response.authorizationRequirements,
        },
      };
    }
    return mapTerminalResponse(response);
  }
}

export async function createBridgeFromConfig(configPath: string): Promise<GeneratedBridge> {
  const absoluteConfigPath = resolve(configPath);
  const configDir = dirname(absoluteConfigPath);
  const config = JSON.parse(await readFile(absoluteConfigPath, "utf8")) as CliConfig;
  return new GeneratedBridge(toProposerConfig(config, configDir));
}

export async function runBridge(argv = process.argv.slice(2)): Promise<void> {
  const configPath = configPathFromArgs(argv);
  const bridge = await createBridgeFromConfig(configPath);
  const server = bridge.buildMcpServer();
  const transport = new StdioServerTransport();

  await server.connect(transport);
}

function toProposerConfig(config: CliConfig, configDir: string): ProposerConfig {
  if (config.mode === "maintainer") {
    throw new Error("Maintainer/signer mode is not supported by this proposer bridge.");
  }
  if (!config.plugin) {
    throw new Error('Proposer bridge config requires "plugin".');
  }
  const pluginPath = resolve(configDir, config.plugin);
  const plugin = loadPlugin(pluginPath);
  const adapterUrl = config.adapter?.url ?? config.adapterUrl;
  const agentKey = config.agent?.keyFile ?? config.agentKey;
  if (!adapterUrl) {
    throw new Error('Proposer bridge config requires "adapter.url".');
  }
  if (!agentKey) {
    throw new Error('Proposer bridge config requires "agent.keyFile".');
  }

  return {
    plugin: pluginPath,
    applicationDid: (config.target?.applicationDid ?? config.applicationDid ?? plugin.applicationDid) as ProposerConfig["applicationDid"],
    adapterUrl,
    agentKey: resolve(configDir, agentKey),
    approvalStrategy: config.approvalStrategy,
    coordinationUrl: config.coordination?.url,
    approvalTimeoutMs: config.approvalTimeoutMs,
    executionProfile: (config.executionProfile ?? {
      id: plugin.executionProfile.id,
      format: plugin.executionProfile.format ?? "mcp.toolsCall",
    }) as ProposerConfig["executionProfile"],
    defaultExpirationMinutes: config.defaultExpirationMinutes,
  };
}

function loadPlugin(plugin: ProposerConfig["plugin"]): MpasApplicationPlugin {
  if (typeof plugin === "string") {
    return JSON.parse(readFileSync(plugin, "utf8")) as MpasApplicationPlugin;
  }

  return plugin;
}

function loadTools(): Tool[] {
  const parsed: unknown = JSON.parse(
    readFileSync(new URL("./tools.json", import.meta.url), "utf8"),
  );
  if (
    !Array.isArray(parsed)
    || parsed.some((tool) => !isRecord(tool) || typeof tool.name !== "string" || !isRecord(tool.inputSchema))
  ) {
    throw new Error("Generated bridge tools.json must contain an array of MCP Tool definitions.");
  }
  return parsed as Tool[];
}

function loadKeyManager(agentKey: ProposerConfig["agentKey"]): Promise<KeyManager> {
  if (typeof agentKey === "string") {
    return KeyManager.fromFile(agentKey);
  }

  return Promise.resolve(KeyManager.fromJwk(agentKey));
}

function configPathFromArgs(argv: string[]): string {
  const configIndex = argv.indexOf("--config");
  const configPath = configIndex >= 0 ? argv[configIndex + 1] : undefined;
  if (!configPath) {
    throw new Error("Usage: mpas-bridge --config <path>");
  }

  return configPath;
}

function toArgsObject(args: unknown): object {
  if (args && typeof args === "object" && !Array.isArray(args)) {
    return args;
  }

  return {};
}

function mapTerminalResponse(response: AdapterResponse): ToolCallResult {
  switch (response.result) {
    case "executed":
      return relayExecutionResult(response.executionResult);
    case "failed":
      return response.executionResult !== undefined
        ? relayExecutionResult(response.executionResult)
        : errorResult(response.error?.code ?? "EXECUTION_FAILED", response.error?.message ?? "Execution failed definitively.", response);
    case "indeterminate":
      return indeterminateResult(response);
    case "pending":
      return pendingResult(response);
    case "rejected":
      return errorResult(response.error?.code ?? "REJECTED", response.error?.message ?? "Action was rejected.", response);
    case "expired":
      return errorResult(response.error?.code ?? "EXPIRED", response.error?.message ?? "Action Envelope expired; a new Action Envelope is required.", response);
    case "cancelled":
      return errorResult(response.error?.code ?? "CANCELLED", response.error?.message ?? "Action was cancelled.", response);
    case "malformed":
      return errorResult(response.error?.code ?? "MALFORMED", response.error?.message ?? "Action Package is malformed.", response);
    case "notSupported":
      return errorResult(response.error?.code ?? "NOT_SUPPORTED", response.error?.message ?? "The Verifier does not support this action.", response);
    case "policyUnavailable":
      return errorResult(response.error?.code ?? "POLICY_UNAVAILABLE", response.error?.message ?? "The Verifier could not evaluate policy; retry later.", response);
    default:
      return errorResult("UNRECOGNIZED_RESULT", `Adapter returned an unrecognized result: ${String((response as { result?: unknown }).result)}.`, response as unknown as Record<string, unknown>);
  }
}

function relayExecutionResult(result: unknown): ToolCallResult {
  if (isRecord(result) && Array.isArray(result.content)) {
    // The adapter returns the upstream MCP CallToolResult. Preserve it
    // verbatim, including structuredContent, resource content, _meta, and
    // future protocol fields, rather than wrapping or projecting it.
    return result as unknown as ToolCallResult;
  }

  return {
    content: [
      {
        type: "text",
        text: result === undefined ? "Action executed." : JSON.stringify(result),
      },
    ],
    ...(result === undefined ? {} : { structuredContent: isRecord(result) ? result : { value: result } }),
  };
}

function errorResult(code: string, message: string, structuredContent?: object): ToolCallResult {
  return {
    isError: true,
    content: [
      {
        type: "text",
        text: `${code}: ${message}`,
      },
    ],
    structuredContent: structuredContent as Record<string, unknown> | undefined,
  };
}

function indeterminateResult(response: AdapterResponse): ToolCallResult {
  return {
    isError: true,
    content: [
      {
        type: "text",
        text: "INDETERMINATE: Execution was dispatched but the outcome could not be confirmed. Do not automatically retry with the same actionId; reconcile out of band and submit a new Action Envelope if needed.",
      },
    ],
    structuredContent: {
      status: "indeterminate",
      executionReceipt: response.executionReceipt,
    },
  };
}

function pendingResult(response: AdapterResponse): ToolCallResult {
  return {
    content: [
      {
        type: "text",
        text: "Action is executing or awaiting execution. No second dispatch will occur for an identical resubmission.",
      },
    ],
    structuredContent: {
      status: "pending",
      actionRequestId: response.actionRequestId,
      pollAfter: response.pollAfter,
    },
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await runBridge();
}
